#!/usr/bin/env bash
# Transfer a file to a remote web server

no_param=$#

if [ $no_param -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$4" -T "$1" "$3"@"$2":
fi
