#!/usr/bin/env bash
# Transfer a file to a remote web server

no_param=$#

if [ "$no_param" -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$4" -o "StrictHostKeyChecking=no" "$1" "$3"@"$2": # -i to specify the location of the ssh key, -o disables strict ssh key checking by server/receipient. ':' is necessary even if a specific dir to connect isnt specified
fi
