#!/usr/bin/env bash
# Install an nginx web server software on a new Ubuntu os server

# Install any ubuntu updates
sudo apt -y update
sudo apt -y upgrade

# Server software installations
sudo apt -y --fix-missing install nginx  # add --allow-downgrades flag when reverting upgrade
sudo apt-get -y --fix-missing install ufw  # add --allow-downgrades flag when reverting upgrade

# Allow nginx to pass through firewall
sudo ufw allow 'Nginx HTTP'

domain="$(curl -s https://ipinfo.io/ip)"  # Get public ip address of server. For internal ip(not recommended except server is to be used only on private networks) use "$(hostname -I)"

# Creating page content
sudo mkdir -p /var/www/"$domain"/html  # -p creates any missing dirs leading to the html dir
sudo chown -R "$USER":"$USER" /var/www/"$domain"/html  # set onership right to the cyrrent user
sudo touch -c /var/www/"$domain"/html/index.html  # -c flag does nothing to the timestamp/file if it exists
sudo chmod -R 755 /var/www/"$domain"/html  # ensure file has required permissions
echo "Hello World!" | sudo tee  /var/www/"$domain"/html/index.html  > /dev/null  # Page must only serve "Hello World" string

# Create server block to serve web content
webroot="/var/www/$domain/html"
config_file="/etc/nginx/sites-available/$domain.conf"
sudo tee "$config_file" > /dev/null <<EOF  # write into the config file specified in $config_file
server {
	listen 80;
	server_name "$domain";

	location / {
		root "$webroot";
		index index.html;
		add_header X-Served-By "$HOSTNAME";
       }
}

EOF

sudo ln -s "$config_file" /etc/nginx/sites-enabled/  # activate/enable server block by making a symbolic link between config file and sites-enabled/ dir. Remove sym link to disable server block of website

# Reload/Start Nginx to apply changes
sudo nginx -s reload
