#!/usr/bin/env bash
# Configure a loadbalancer after installing/configuring an nginx server and other packages on a bew ubuntu os

# Install any ubuntu updates
sudo apt -y update
sudo apt -y upgrade

# Server software installations
sudo apt -y --fix-missing install nginx  # add --allow-downgrades flag when reverting upgrade
sudo apt-get -y --fix-missinginstall ufw  # add --allow-downgrades flag when reverting upgrade

# Allow nginx to pass through firewall
sudo ufw allow 'Nginx HTTP'

# Creating page content
sudo mkdir -p /var/www/18.235.249.119/html  # -p creates any missing dirs leading to the html dir
sudo chown -R "$USER":"$USER" /var/www/18.235.249.119/html  # set onership right to the current user
sudo touch -c /var/www/18.235.249.119/html/index.html  # -c flag does nothing to the timestamp/file if it exists
sudo chmod -R 755 /var/www/18.235.249.119/html  # ensure file has required permissions
echo "Hello World!" | sudo tee  /var/www/18.235.249.119/html/index.html  > /dev/null  # Page must only serve "Hello World" string


# Create server block to serve web content
domain='18.235.249.119'
webroot='/var/www/18.235.249.119/html'
config_file="/etc/nginx/sites-available/$domain.conf"
sudo tee "$config_file" > /dev/null <<EOF  # write into the config file specified in $config_file
server {
	listen 80;
	server_name "$domain";

	location / {
		root "$webroot";
		index index.html;
       }
}

EOF

sudo ln -s "$config_file" /etc/nginx/sites-enabled/  # activate/enable server block by making a symbolic link between config file and sites-enabled/ dir. Remove sym link to disable server block of website

# Reload/Start Nginx to apply changes
sudo nginx -s reload


# INSTALL HAProxy FOR LOADBALANCER
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8  # Add repo for installation
sudo apt-get install haproxy=2.8.\*

# Setup the Load balancer config file
load_balancer_conf='/'
sudo tee 
