#!/usr/bin/env bash
#Prints "bad luck" for the 4th loop iteration, display "good luck" for the 8th
#loop iteration and display "Best School" for the other iterations

i=1
while [ "$i" -le 10 ]
do
    if [ "$i" -eq 4 ]
    then
	echo "bad luck"
    elif [ "$i" -eq 8 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi
    (( i++ ))
done
