#!/usr/bin/env bash
# Prints content of the current directory, in a list format with a filter

cwd=.
for i in "$cwd"/*
do
#    if [ -f "$i" ] || [ -h "$i" ] || [ -b  "$i" ] || [ -p "$i" ]
#    then
    echo "$i" | cut -d '-' -f 2-
#    fi
done
