#!/usr/bin/env bash
# Prints content of the current directory, in a list format with a filter

cwd=.
for i in "$cwd"/*
do
    if [ -f "$i" ]
    then
	echo "$i" | grep "-" | cut -d '-' -f 2-
    fi
done
