#!/usr/bin/env bash
# Changes device localhost and facebook ip address stored
cp /etc/hosts ./hosts.new
sudo sed -i 's/^127.0.0.1\s+localhost/127.0.0.2    localhost/g' ./hosts.new
sudo sed -i 's/^157.240.11.35\s+facebook.com/8.8.8.8    facebook.com/g' ./hosts.new
cat ./hosts.new > /etc/hosts
rm ./hosts.new
