#!/usr/bin/env bash
# Changes device localhost and facebook ip address stored
sudo cp /etc/hosts ./hosts.new
sed -i 's/^127.0.0.1.+localhost$/127.0.0.2    localhost/g' ./hosts.new
sed -i 's/^157.240.11.35.+facebook.com/8.8.8.8    facebook.com/g' ./hosts.new
cat ./hosts.new > /etc/hosts
rm ./hosts.new
cat /etc/hosts
